export const EMPLOYEE_EXPORT_QUEUE = "employee-export";

export const EMPLOYEE_EXPORT_JOB = "employee-export-run";

export const EMPLOYEE_EXPORT_CLEANUP_JOB = "employee-export-cleanup";

export const EMPLOYEE_EXPORT_CLEANUP_JOB_ID = "employee-export-cleanup";

export const EMPLOYEE_EXPORT_BATCH_SIZE = 500;

export const EMPLOYEE_EXPORT_TTL_MS = 24 * 60 * 60 * 1_000;

export const EMPLOYEE_EXPORT_MAX_ATTEMPTS = 3;

export const EMPLOYEE_EXPORT_CLEANUP_EVERY_MS = 60 * 60 * 1_000;

export const EMPLOYEE_EXPORT_CLEANUP_BATCH = 100;

export const EMPLOYEE_EXPORT_ERROR_CODES = {
  EXPORT_NOT_FOUND: "EMPLOYEE_EXPORT_NOT_FOUND",
  EXPORT_INVALID_STATE: "EMPLOYEE_EXPORT_INVALID_STATE",
  EXPORT_QUEUE_UNAVAILABLE: "EMPLOYEE_EXPORT_QUEUE_UNAVAILABLE",
  EXPORT_WORKER_FAILED: "EMPLOYEE_EXPORT_WORKER_FAILED",
} as const;
