export const EMPLOYEE_IMPORT_QUEUE = "employee-import";

export const EMPLOYEE_IMPORT_VALIDATE_JOB = "employee-import-validate";

export const EMPLOYEE_IMPORT_APPLY_JOB = "employee-import-apply";

export const EMPLOYEE_IMPORT_CLEANUP_JOB = "employee-import-cleanup";

export const EMPLOYEE_IMPORT_CLEANUP_JOB_ID = "employee-import-cleanup";

export const EMPLOYEE_IMPORT_APPLY_BATCH_SIZE = 200;

export const EMPLOYEE_IMPORT_NORMALIZED_CHUNK_SIZE = 500;

export const EMPLOYEE_IMPORT_MAX_FILE_BYTES = 25 * 1024 * 1024;

export const EMPLOYEE_IMPORT_MAX_ROWS = 100_000;

export const EMPLOYEE_IMPORT_TTL_MS = 24 * 60 * 60 * 1_000;

export const EMPLOYEE_IMPORT_MAX_ATTEMPTS = 3;

export const EMPLOYEE_IMPORT_CLEANUP_EVERY_MS = 60 * 60 * 1_000;

export const EMPLOYEE_IMPORT_CLEANUP_BATCH = 100;

export const EMPLOYEE_IMPORT_ERROR_CODES = {
  IMPORT_NOT_FOUND: "EMPLOYEE_IMPORT_NOT_FOUND",
  IMPORT_INVALID_STATE: "EMPLOYEE_IMPORT_INVALID_STATE",
  IMPORT_FILE_TOO_LARGE: "EMPLOYEE_IMPORT_FILE_TOO_LARGE",
  IMPORT_UNSUPPORTED_TYPE: "EMPLOYEE_IMPORT_UNSUPPORTED_TYPE",
  IMPORT_VALIDATION_FAILED: "EMPLOYEE_IMPORT_VALIDATION_FAILED",
  IMPORT_CONFLICT: "EMPLOYEE_IMPORT_CONFLICT",
  IMPORT_WORKER_FAILED: "EMPLOYEE_IMPORT_WORKER_FAILED",
} as const;
