export const ACCESS_COOKIE_NAME = "paylens_at";

export const REFRESH_COOKIE_NAME = "paylens_rt";

export const SESSION_HINT_COOKIE_NAME = "paylens_session_hint";

export const OAUTH_STATE_TTL_SECONDS = 600;

export const ACCESS_TOKEN_TTL_SECONDS = 900;

export const REFRESH_TOKEN_TTL_SECONDS = 1_209_600;

export const OAUTH_STATE_COOKIE_NAME = "paylens_oauth";

export const EMAIL_VERIFICATION_TTL_HOURS = 24;

export const PASSWORD_RESET_TTL_MINUTES = 30;

export const INVITATION_TTL_DAYS = 7;

export const PASSWORD_MIN_LENGTH = 12;

export const PASSWORD_MAX_LENGTH = 128;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  EMAIL_VERIFICATION_TOKEN_INVALID: "EMAIL_VERIFICATION_TOKEN_INVALID",
  EMAIL_VERIFICATION_TOKEN_EXPIRED: "EMAIL_VERIFICATION_TOKEN_EXPIRED",
  PASSWORD_RESET_TOKEN_INVALID: "PASSWORD_RESET_TOKEN_INVALID",
  PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
  INVITATION_INVALID: "INVITATION_INVALID",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_ALREADY_USED: "INVITATION_ALREADY_USED",
  INVITATION_EMAIL_MISMATCH: "INVITATION_EMAIL_MISMATCH",
  MEMBERSHIP_REQUIRED: "MEMBERSHIP_REQUIRED",
  MEMBERSHIP_SUSPENDED: "MEMBERSHIP_SUSPENDED",
  INSUFFICIENT_PERMISSION: "INSUFFICIENT_PERMISSION",
  ORGANIZATION_SELECTION_REQUIRED: "ORGANIZATION_SELECTION_REQUIRED",
  GOOGLE_AUTH_DISABLED: "GOOGLE_AUTH_DISABLED",
  GOOGLE_AUTH_FAILED: "GOOGLE_AUTH_FAILED",
  OAUTH_STATE_INVALID: "OAUTH_STATE_INVALID",
  OAUTH_IDENTITY_CONFLICT: "OAUTH_IDENTITY_CONFLICT",
  CSRF_ORIGIN_FORBIDDEN: "CSRF_ORIGIN_FORBIDDEN",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

/** Roles ordered from most to least privilege for invitation checks. */
export const ROLE_RANK = {
  TENANT_OWNER: 6,
  HR_ADMIN: 5,
  HR_MANAGER: 4,
  MANAGER: 3,
  EMPLOYEE: 2,
  VIEWER_AUDITOR: 1,
} as const;

export type MembershipRoleName = keyof typeof ROLE_RANK;

/** Which roles each role may invite (auth phase, §7). */
export const INVITE_PERMISSIONS: Record<MembershipRoleName, readonly MembershipRoleName[]> = {
  TENANT_OWNER: ["HR_ADMIN", "HR_MANAGER", "MANAGER", "EMPLOYEE", "VIEWER_AUDITOR"],
  HR_ADMIN: ["HR_MANAGER", "MANAGER", "EMPLOYEE", "VIEWER_AUDITOR"],
  HR_MANAGER: ["EMPLOYEE"],
  MANAGER: [],
  EMPLOYEE: [],
  VIEWER_AUDITOR: [],
};

export const DEFAULT_SAFE_REDIRECT = "/dashboard";
